spring.application.name=smart-campus-backend
server.port=8082

spring.mongodb.uri=${MONGO_URI}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true
