spring.application.name=smart-campus-backend
server.port=8081

# ===== File uploads =====
spring.mongodb.uri=mongodb+srv://Kavindu_Maree:kavin567@event.puotuo9.mongodb.net/smartCampusDB?retryWrites=true&w=majority&appName=EVENT
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true

# ===== OAuth2 - Google =====
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ===== Logging =====
logging.level.com.smartcampus=INFO
logging.level.org.springframework.security=INFO

server.port=8080
spring.mongodb.uri=mongodb+srv://Gayani_Lowe:Gayani567@event.puotuo9.mongodb.net/smartCampusDB?retryWrites=true&w=majority&appName=EVEN
